# APIS Configuration Constants

# Serial Settings
SERIAL_BAUDRATE = 9600
SERIAL_TIMEOUT_S = 0.5  # Readline timeout for fast non-blocking feel

# Connection & Logic
MAX_RETRIES = 3
CONNECTION_WAIT_S = 2.0  # Max wait for READY handshake
SETTLING_TIME_S = 1.5    # Default physical settling time (software enforced)
COMMAND_DELAY_S = 0.05   # Min delay between commands to avoid flooding

# Servo Motion Limits
SERVO_MIN_ANGLE = 0
SERVO_MAX_ANGLE = 180

# XIMEA Acquisition Defaults
XIMEA_USE_FIXED_WB = True
XIMEA_WB_KR = 1.40
XIMEA_WB_KG = 1.00
XIMEA_WB_KB = 1.20
XIMEA_DEFAULT_PPL_EXPOSURE_US = 18000
XIMEA_DEFAULT_XPL_EXPOSURE_US = 400000
XIMEA_DEFAULT_POLARIZER_CALIBRATION_EXPOSURE_US = XIMEA_DEFAULT_XPL_EXPOSURE_US
XPL_LOCAL_CALIBRATION_EXPOSURE_US = XIMEA_DEFAULT_XPL_EXPOSURE_US

# Backward-compatible aliases for older mode-name references.
XIMEA_DEFAULT_NORMAL_EXPOSURE_US = XIMEA_DEFAULT_PPL_EXPOSURE_US
XIMEA_DEFAULT_CROSSPOL_EXPOSURE_US = XIMEA_DEFAULT_XPL_EXPOSURE_US

# Mechanical Transmission
SERVO_GEAR_TEETH = 70
STAGE_GEAR_TEETH = 80

# Convert requested stage angle into servo angle.
# servo_angle = zero_offset + direction * stage_angle * ratio
# Both axes currently use an image-derived calibration ratio from a PPL reference capture set.
POLARIZER_STAGE_TO_SERVO_RATIO = 1.059
SAMPLE_STAGE_TO_SERVO_RATIO = 1.059
POLARIZER_STAGE_DIRECTION = 1
SAMPLE_STAGE_DIRECTION = 1
POLARIZER_SERVO_ZERO_DEG = 0
SAMPLE_SERVO_ZERO_DEG = 0
POLARIZER_PPL_ANGLE_DEG = 5
POLARIZER_XPL_ANGLE_DEG = 95
POLARIZER_CALIBRATION_SIGNAL_ROI_SIZE_PX = 500
XPL_LOCAL_CALIBRATION_RADIUS_DEG = 10
XPL_LOCAL_CALIBRATION_STEP_DEG = 1
XPL_ADAPTIVE_COARSE_ANGLES_DEG = [90, 100, 110, 120, 130, 140, 150]
XPL_LOCAL_COARSE_TRIGGER_MEAN = 80.0
XPL_LOCAL_FINE_MAX_SPAN_DEG = 30
XPL_LOCAL_FINE_STOP_INCREASE_COUNT = 2
XPL_LOCAL_FINE_STOP_RATIO = 1.2
XPL_LOCAL_CALIBRATION_FINAL_APPROACH_OFFSET_DEG = 5
XPL_LOCAL_CONFIRMATION_MAX_MEAN = 65.0
XPL_LOCAL_CONFIRMATION_MAX_RATIO = 1.2
XPL_LOCAL_CONFIRMATION_REFINE_RADIUS_DEG = 5
XPL_LOCAL_CONFIRMATION_MAX_REFINES = 2
XPL_BACKGROUND_ROI_X = 700
XPL_BACKGROUND_ROI_TOP_Y = 0
XPL_BACKGROUND_ROI_BOTTOM_Y = 1000
XPL_BACKGROUND_ROI_WIDTH = 700
XPL_BACKGROUND_ROI_HEIGHT = 80
POLARIZER_STAGE_MIN_ANGLE = 0
SAMPLE_STAGE_MIN_ANGLE = 0
POLARIZER_STAGE_MAX_ANGLE = int((SERVO_MAX_ANGLE - POLARIZER_SERVO_ZERO_DEG) / POLARIZER_STAGE_TO_SERVO_RATIO)
SAMPLE_STAGE_MAX_ANGLE = int((SERVO_MAX_ANGLE - SAMPLE_SERVO_ZERO_DEG) / SAMPLE_STAGE_TO_SERVO_RATIO)

# Command Codes (Protocol PPAAA)
CMD_POLARIZER = 10
CMD_SAMPLE    = 11
CMD_HOME      = 96
CMD_RESET     = 98
CMD_ESTOP     = 99

# Safety States
STATE_LATCHED = "LATCHED"  # Detached, Boot/Estop
STATE_ARMED   = "ARMED"    # Attached, Normal Operation
